---
- hosts: localhost
  gather_facts: False

  tasks:
    - name: Create OCP 4 vCenter Role
      import_role:
        name: create_ocp4_vcenter_roles

    - name: Apply OCP 4 vCenter Role
      import_role:
        name: apply_roles_precreated_folder
      when: openshift.installer_created_folder != True

    - name: Apply OCP 4 vCenter Role
      import_role:
        name: apply_roles_installer_created_folder
      when: openshift.installer_created_folder == True
