---
- name: Create openshift-vcenter-level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-vcenter_level
    local_privilege_ids: "{{ vcenter_level }}"
    state: present

- name: Create openshift-cluster-level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-cluster_level
    local_privilege_ids: "{{ cluster_level }}"
    state: present

- name: Create openshift-datastore_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-datastore_level
    local_privilege_ids: "{{ datastore_level }}"
    state: present

- name: Create openshift-portgroup_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-portgroup_level
    local_privilege_ids: "{{ portgroup_level }}"
    state: present

- name: Create openshift-folder_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-folder_level
    local_privilege_ids: "{{ folder_level }}"
    state: present
  when: openshift.installer_created_folder == False

- name: Create openshift-datacenter_level role
  vmware_local_role_manager:
    hostname: "{{ vcenter.ip }}"
    username: "{{ vcenter.admin_username }}"
    password: "{{ vcenter.admin_password }}"
    validate_certs: no
    local_role_name: openshift-datacenter_level
    local_privilege_ids: "{{ datacenter_level }}"
    state: present
  when: openshift.installer_created_folder == True
